In [1]:
!pip install -q 'fugashi[unidic-lite]==1.5.2'

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.4/47.4 MB 17.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 691.4/691.4 kB 10.1 MB/s eta 0:00:00


In [2]:
import torch
from transformers import AutoModel, AutoTokenizer

In [3]:
# トークナイザーとモデルを読み込む
MODEL_NAME = "tohoku-nlp/bert-base-japanese-v3"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModel.from_pretrained(MODEL_NAME)

# テキストをトークンに分割する
input_text = "TransformerはNLPに革命を起こした。"
inputs = tokenizer(input_text, return_tensors="pt")
input_ids = inputs["input_ids"]
print(input_ids)

# トークン埋め込みを取得する
with torch.no_grad():
  embeddings = model.get_input_embeddings()(input_ids)
print(embeddings)

/usr/local/lib/python3.13/dist-packages/huggingface_hub/utils/_auth.py:138: UserWarning: 
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
  warnings.warn(f"\nError while fetching `HF_TOKEN` secret value from your vault: '{str(e)}'.")


config.json:   0%|          | 0.00/472 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/251 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/231k [00:00<?, ?B/s]

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  447MB            

pytorch_model.bin: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: tohoku-nlp/bert-base-japanese-v3
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 
cls.seq_relationship.bias                  | UNEXPECTED |  | 
cls.predictions.decoder.bias               | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 
cls.predictions.decoder.weight             | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


tensor([[    2, 25097, 23784, 12544,   465,    61,  7159,  7135,   461, 14197,
           500, 14466,   449,   385,     3]])
tensor([[[-0.0325, -0.0099,  0.0031,  ...,  0.0205,  0.0168,  0.0543],
         [-0.0180,  0.0017, -0.0326,  ..., -0.0111,  0.0427,  0.1389],
         [-0.0166, -0.0286, -0.0434,  ...,  0.0115,  0.0161,  0.0692],
         ...,
         [-0.0456, -0.0116,  0.0635,  ...,  0.0072,  0.0363,  0.0529],
         [ 0.0258, -0.0366,  0.0035,  ..., -0.0029, -0.0344,  0.0457],
         [-0.0413, -0.0007,  0.0178,  ...,  0.0273, -0.0118,  0.0055]]])


In [4]:
input_ids.shape

torch.Size([1, 15])

In [5]:
# Accessing the positional embeddings (indirectly)
# Note: This is more of an illustrative purpose. For specific models like BERT, positional embeddings are not directly exposed.
# However, you can access the model's embeddings layer and look at the weights for the positional embeddings.
positional_embeddings = model.embeddings.position_embeddings.weight
print(positional_embeddings)

# If you want to see the effect of positional embeddings on a specific token,
# you can compare the embeddings with and without positional information.
# Note: This is a conceptual demonstration and may not directly apply as is.
token_without_position = model.embeddings.word_embeddings(input_ids[0])
token_with_position = embeddings[0]

print("Token without positional information:", token_without_position)
print("Token with positional information:", token_with_position)


Parameter containing:
tensor([[ 0.0228,  0.0261, -0.0007,  ..., -0.0043, -0.0208,  0.0148],
        [-0.0224,  0.0305, -0.0178,  ...,  0.0040,  0.0232, -0.0730],
        [-0.0155,  0.0222, -0.0138,  ...,  0.0222,  0.0306, -0.0535],
        ...,
        [-0.0092, -0.0104, -0.0118,  ..., -0.0175,  0.0227, -0.0320],
        [-0.0131, -0.0037,  0.0120,  ...,  0.0148,  0.0303, -0.0254],
        [ 0.0032,  0.0447,  0.0493,  ...,  0.0422, -0.0172,  0.0885]],
       requires_grad=True)
Token without positional information: tensor([[-0.0325, -0.0099,  0.0031,  ...,  0.0205,  0.0168,  0.0543],
        [-0.0180,  0.0017, -0.0326,  ..., -0.0111,  0.0427,  0.1389],
        [-0.0166, -0.0286, -0.0434,  ...,  0.0115,  0.0161,  0.0692],
        ...,
        [-0.0456, -0.0116,  0.0635,  ...,  0.0072,  0.0363,  0.0529],
        [ 0.0258, -0.0366,  0.0035,  ..., -0.0029, -0.0344,  0.0457],
        [-0.0413, -0.0007,  0.0178,  ...,  0.0273, -0.0118,  0.0055]],
       grad_fn=<EmbeddingBackward0>)
Token wi

In [6]:
position_ids = torch.arange(512).expand((1, -1))


In [7]:
position_embeddings = model.embeddings.position_embeddings(position_ids)

In [8]:
position_embeddings.shape

torch.Size([1, 512, 768])